### ISSUE TITLE
font-weight: bold not necessary on h1 and h2

### ISSUE THREAD

**Issue by jzhu01** [tela1505/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/tela1505/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/css/index.css#L4

Since the h1s and h2s are already bolded by default, adding this line doesn't change the display.

**Comment by tela1505** [comment]
Solved
