### ISSUE TITLE
Since you repeat the font-family styling for most elements, it makes sense to select body or all the elements once and apply it

### ISSUE THREAD

**Issue by jzhu01** [tela1505/prj-rev-bwfs-dasmoto#4]
Seen here: https://github.com/tela1505/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/css/index.css#L2

It makes more sense to either select body and apply it once, or to list all the HTML elements and then apply the font-family once.

**Comment by tela1505** [comment]
Solved
